version: "3.2"
services:
  compliancehub-plugin-trivy:
    image: chplugintrivy
    container_name: compliancehub-plugin-trivy        
    privileged: true
    hostname: compliancehub-plugin-trivy
    environment:
      - CH_TRIVY_REMOTE=http://trivy-server:5005
      - CH_SERVER_ADDRESS=0.0.0.0
    networks: 
      - trivy_network
    ports:
      - '5004:5004'
  trivy-server:
    image: aquasec/trivy:0.18.0
    container_name: trivy-server    
    command: server --listen ':5005'
    privileged: true
    hostname: trivy_server
    networks: 
      - trivy_network
    ports:      
      - '5005:5005'
    volumes:
      - './trivy-server/output:/trivy-server/output'
networks:
  trivy_network: