version: "3.2"
services:
  compliancehub-plugin-trivy:
    image: chplugintrivy
    container_name: compliancehub-plugin-trivy        
    privileged: true
    hostname: compliancehub-plugin-trivy
    environment:
      - CH_TRIVY_REMOTE="http://trivy-server:5004"
    networks: 
      - trivy_network
    ports:
      - '5003:5003'
    volumes:      
      - '/var/run/docker.sock:/var/run/docker.sock'
  trivy-server:
    image: aquasec/trivy:latest
    container_name: trivy-server    
    command: server --listen ':5004'
    privileged: true
    hostname: trivy_server
    networks: 
      - trivy_network
    ports:      
      - '5004:5004'
    volumes:
      - './trivy-server/output:/trivy-server/output'
      - '/var/run/docker.sock:/var/run/docker.sock'    
networks:
  trivy_network:

  